<a href="https://colab.research.google.com/github/kdemertzis/EKPA/blob/main/Diabetes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
data = pd.read_csv('https://raw.githubusercontent.com/kdemertzis/EKPA/main/Data/phishing_dataset.csv', delimiter=',')

In [2]:
data = data.sample(frac=1).reset_index(drop=True)
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            3      141              0              0        0  30.0   
1           12      151             70             40      271  41.8   
2            4       84             90             23       56  39.5   
3            1       80             55              0        0  19.1   
4            5      128             80              0        0  34.6   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.761   27        1  
1                     0.742   38        1  
2                     0.159   25        0  
3                     0.258   21        0  
4                     0.144   45        0

In [3]:
X = data.drop(['Domain', 'Label'], axis=1)

In [4]:
X.head()

Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0      141              0              0        0  30.0   
1      151             70             40      271  41.8   
2       84             90             23       56  39.5   
3       80             55              0        0  19.1   
4      128             80              0        0  34.6   

   DiabetesPedigreeFunction  Age  
0                     0.761   27  
1                     0.742   38  
2                     0.159   25  
3                     0.258   21  
4                     0.144   45

In [5]:
#y=np.ravel(data['Label'])
y=np.ravel(data['Outcome'])

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=43)

In [7]:
# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
# Define classifiers
classifiers = [
    LogisticRegression(),
    SVC(),
    RandomForestClassifier(),
    MLPClassifier(),
    KNeighborsClassifier(),
    DecisionTreeClassifier()
]

In [9]:
# Evaluate and compare classifiers
results = {'Classifier': [], 'Accuracy': [], 'Precision': [], 'Recall': [], 'F1 Score': []}

for clf in classifiers:
    clf_name = clf.__class__.__name__

    # Train the classifier
    clf.fit(X_train, y_train)

    # Make predictions
    y_pred = clf.predict(X_test)

    # Calculate evaluation metrics
    acc = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')

    # Confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Display results
    print(f"\n{clf_name} Metrics:")
    print(f"Accuracy: {acc}")
    print(f"Precision: {precision}")
    print(f"Recall: {recall}")
    print(f"F1 Score: {f1}")
    print("Confusion Matrix:")
    print(cm)

    # Store results for comparison
    results['Classifier'].append(clf_name)
    results['Accuracy'].append(acc)
    results['Precision'].append(precision)
    results['Recall'].append(recall)
    results['F1 Score'].append(f1)


LogisticRegression Metrics:
Accuracy: 0.7575757575757576
Precision: 0.7511478420569329
Recall: 0.7575757575757576
F1 Score: 0.7528275714895434
Confusion Matrix:
[[132  23]
 [ 33  43]]

SVC Metrics:
Accuracy: 0.7662337662337663
Precision: 0.7621682665160926
Recall: 0.7662337662337663
F1 Score: 0.7636496501591005
Confusion Matrix:
[[131  24]
 [ 30  46]]

RandomForestClassifier Metrics:
Accuracy: 0.7402597402597403
Precision: 0.7385762799775538
Recall: 0.7402597402597403
F1 Score: 0.7393606393606394
Confusion Matrix:
[[126  29]
 [ 31  45]]

MLPClassifier Metrics:
Accuracy: 0.7619047619047619
Precision: 0.761123321123321
Recall: 0.7619047619047619
F1 Score: 0.7614991568484893
Confusion Matrix:
[[128  27]
 [ 28  48]]

KNeighborsClassifier Metrics:
Accuracy: 0.7662337662337663
Precision: 0.7647358666466947
Recall: 0.7662337662337663
F1 Score: 0.7654245754245753
Confusion Matrix:
[[129  26]
 [ 28  48]]

DecisionTreeClassifier Metrics:
Accuracy: 0.7142857142857143
Precision: 0.714285714285714

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [10]:
# Display comparison results
results_df = pd.DataFrame(results)
results_df = results_df.sort_values(by='Accuracy', ascending=False)
print("\nComparison of Classifiers:")
print(results_df)


Comparison of Classifiers:
               Classifier  Accuracy  Precision    Recall  F1 Score
1                     SVC  0.766234   0.762168  0.766234  0.763650
4    KNeighborsClassifier  0.766234   0.764736  0.766234  0.765425
3           MLPClassifier  0.761905   0.761123  0.761905  0.761499
0      LogisticRegression  0.757576   0.751148  0.757576  0.752828
2  RandomForestClassifier  0.740260   0.738576  0.740260  0.739361
5  DecisionTreeClassifier  0.714286   0.714286  0.714286  0.714286
